# Generated by Django 4.2.30 on 2026-04-17 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialbooking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorialbooking',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_bookings', to='bookings.course'),
        ),
        migrations.AddField(
            model_name='tutorialbooking',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_bookings', to='halls.hall'),
        ),
        migrations.AddField(
            model_name='tutorialbooking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_bookings', to='bookings.timeslot'),
        ),
    ]
