from campus_system.api_views import (
    bookings_resource,
    call_off_booking,
    cancel_booking,
    courses_list,
    fixed_timetable_list,
    fixed_timetable_upload,
    halls_availability_for_slot,
    public_seating_lookup,
    seating_assignment_lookup,
    seating_assignments_list,
    seating_assignments_upload,
    staff_analytics,
    time_slots_list,
)

__all__ = [
    "courses_list",
    "time_slots_list",
    "bookings_resource",
    "cancel_booking",
    "call_off_booking",
    "staff_analytics",
    "fixed_timetable_list",
    "fixed_timetable_upload",
    "halls_availability_for_slot",
    "seating_assignments_list",
    "seating_assignments_upload",
    "seating_assignment_lookup",
    "public_seating_lookup",
]
