# Generated by Django 4.2.30 on 2026-04-17 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialclass',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
