# Generated by Django 4.2.30 on 2026-04-17 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booked', 'Booked'), ('booking_cancelled', 'Booking Cancelled'), ('class_called_off', 'Class Called Off'), ('checked_in_keypad', 'Checked In Keypad')], default='booked', max_length=40)),
                ('lecturer_name', models.CharField(default='', max_length=255)),
                ('auditorium', models.CharField(default='', max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('time', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
